// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package dict

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TranslaterClient is the client API for Translater service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TranslaterClient interface {
	Dictionary(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type translaterClient struct {
	cc grpc.ClientConnInterface
}

func NewTranslaterClient(cc grpc.ClientConnInterface) TranslaterClient {
	return &translaterClient{cc}
}

func (c *translaterClient) Dictionary(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/dict.Translater/Dictionary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TranslaterServer is the server API for Translater service.
// All implementations must embed UnimplementedTranslaterServer
// for forward compatibility
type TranslaterServer interface {
	Dictionary(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedTranslaterServer()
}

// UnimplementedTranslaterServer must be embedded to have forward compatible implementations.
type UnimplementedTranslaterServer struct {
}

func (UnimplementedTranslaterServer) Dictionary(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dictionary not implemented")
}
func (UnimplementedTranslaterServer) mustEmbedUnimplementedTranslaterServer() {}

// UnsafeTranslaterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranslaterServer will
// result in compilation errors.
type UnsafeTranslaterServer interface {
	mustEmbedUnimplementedTranslaterServer()
}

func RegisterTranslaterServer(s grpc.ServiceRegistrar, srv TranslaterServer) {
	s.RegisterService(&Translater_ServiceDesc, srv)
}

func _Translater_Dictionary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslaterServer).Dictionary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dict.Translater/Dictionary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslaterServer).Dictionary(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Translater_ServiceDesc is the grpc.ServiceDesc for Translater service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Translater_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dict.Translater",
	HandlerType: (*TranslaterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dictionary",
			Handler:    _Translater_Dictionary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dict/dict.proto",
}
