// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package dbapp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UsersInfoClient is the client API for UsersInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsersInfoClient interface {
	PostUser(ctx context.Context, in *PostUserReq, opts ...grpc.CallOption) (*UserProfile, error)
	GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserProfile, error)
	UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UserProfile, error)
	DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*UserProfile, error)
}

type usersInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersInfoClient(cc grpc.ClientConnInterface) UsersInfoClient {
	return &usersInfoClient{cc}
}

func (c *usersInfoClient) PostUser(ctx context.Context, in *PostUserReq, opts ...grpc.CallOption) (*UserProfile, error) {
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, "/dbapp.UsersInfo/PostUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersInfoClient) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserProfile, error) {
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, "/dbapp.UsersInfo/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersInfoClient) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UserProfile, error) {
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, "/dbapp.UsersInfo/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersInfoClient) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*UserProfile, error) {
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, "/dbapp.UsersInfo/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersInfoServer is the server API for UsersInfo service.
// All implementations must embed UnimplementedUsersInfoServer
// for forward compatibility
type UsersInfoServer interface {
	PostUser(context.Context, *PostUserReq) (*UserProfile, error)
	GetUser(context.Context, *GetUserReq) (*UserProfile, error)
	UpdateUser(context.Context, *UpdateUserReq) (*UserProfile, error)
	DeleteUser(context.Context, *DeleteUserReq) (*UserProfile, error)
	mustEmbedUnimplementedUsersInfoServer()
}

// UnimplementedUsersInfoServer must be embedded to have forward compatible implementations.
type UnimplementedUsersInfoServer struct {
}

func (UnimplementedUsersInfoServer) PostUser(context.Context, *PostUserReq) (*UserProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostUser not implemented")
}
func (UnimplementedUsersInfoServer) GetUser(context.Context, *GetUserReq) (*UserProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUsersInfoServer) UpdateUser(context.Context, *UpdateUserReq) (*UserProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedUsersInfoServer) DeleteUser(context.Context, *DeleteUserReq) (*UserProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedUsersInfoServer) mustEmbedUnimplementedUsersInfoServer() {}

// UnsafeUsersInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersInfoServer will
// result in compilation errors.
type UnsafeUsersInfoServer interface {
	mustEmbedUnimplementedUsersInfoServer()
}

func RegisterUsersInfoServer(s grpc.ServiceRegistrar, srv UsersInfoServer) {
	s.RegisterService(&UsersInfo_ServiceDesc, srv)
}

func _UsersInfo_PostUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersInfoServer).PostUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbapp.UsersInfo/PostUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersInfoServer).PostUser(ctx, req.(*PostUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersInfo_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersInfoServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbapp.UsersInfo/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersInfoServer).GetUser(ctx, req.(*GetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersInfo_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersInfoServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbapp.UsersInfo/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersInfoServer).UpdateUser(ctx, req.(*UpdateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersInfo_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersInfoServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbapp.UsersInfo/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersInfoServer).DeleteUser(ctx, req.(*DeleteUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UsersInfo_ServiceDesc is the grpc.ServiceDesc for UsersInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsersInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbapp.UsersInfo",
	HandlerType: (*UsersInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostUser",
			Handler:    _UsersInfo_PostUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UsersInfo_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UsersInfo_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UsersInfo_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dbapp/dbapp.proto",
}
